// lib/data.ts

export const artworks = [
  {
    id: 'piece-1893',
    title: 'Study 1893',
    price: 400,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1893.jpeg',
  },
  {
    id: 'piece-1900',
    title: 'Study 1900',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '36 x 24 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1900.jpeg',
  },
  {
    id: 'piece-1903',
    title: 'Study 1903',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1903.jpeg',
  },
  {
    id: 'piece-1924',
    title: 'Study 1924',
    price: 500,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1924.jpeg',
  },
  {
    id: 'piece-1925',
    title: 'Study 1925',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '14 x 18 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1925.jpeg',
  },
  {
    id: 'piece-1927',
    title: 'Study 1927',
    price: 475,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1927.jpeg',
  },
  {
    id: 'piece-1930',
    title: 'Study 1930',
    price: 500,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '18 x 24 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1930.jpeg',
  },
  {
    id: 'piece-1933',
    title: 'Study 1933',
    price: 520,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '18 x 36 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1933.jpeg',
  },
  {
    id: 'piece-1955',
    title: 'Study 1955',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '24 x 36 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1955.jpeg',
  },
  {
    id: 'piece-1957',
    title: 'Study 1957',
    price: 480,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1957.jpeg',
  },
  {
    id: 'piece-1958',
    title: 'Study 1958',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '8 x 10 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1958.jpeg',
  },
  {
    id: 'autumn-river', 
    title: 'Autumn River',
    price: 520,
    collection: 'Seasonal',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "A beautiful autumn river scene with vibrant orange and yellow trees lining the banks.",
    image_url: '/artworks/IMG_1959.jpeg', 
  },
  {
    id: 'piece-1963',
    title: 'Study 1963',
    price: 550,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '10.5 x 13.5 in',
    description: "An original piece from the studio collection.",
    image_url: '/artworks/IMG_1963.jpeg',
  }
];