// lib/data.ts

export const artworks = [
  {
    id: 'wild-flowers-by-the-river',
    title: 'Wild Flowers by the river',
    price: 145,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A vibrant landscape capturing a serene blue stream flowing through a lush meadow. Yellow wildflowers dot the foreground, leading the eye toward evergreen pines and majestic, snow-capped mountain peaks.",
    image_url: '/artworks/alpine-stream.jpeg',
  },
  {
    id: 'october-bend',
    title: 'October Bend',
    price: 450,
    notForSale: true,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '24 x 36 in',
    description: "An autumnal landscape featuring a tranquil river curving through a forest ablaze with vivid red, orange, and yellow foliage, perfectly mirrored in the still water.",
    image_url: '/artworks/october-bend.jpeg',
  },
  {
    id: 'morning-calm-by-the-sea',
    title: 'Morning Calm by the sea',
    price: 75,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A tranquil coastal scene portraying gentle waves washing onto a sandy beach. The soft, pastel-hued sky and pale blue waters evoke the quiet stillness of early morning.",
    image_url: '/artworks/pastel-horizon.jpeg',
  },
  {
    id: 'sunbreak',
    title: 'Sunbeam over blue waters',
    price: 145,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A dramatic seascape highlighting a brilliant sunburst breaking through the clouds. The radiant light creates a striking reflection across the deep blue, cresting ocean waves.",
    image_url: '/artworks/sunbreak.jpeg',
  },
  {
    id: 'turquoise-tides-in-motion',
    title: 'Turquoise Tides in Motion',
    price: 185,
    collection: 'Studio Collection',
    medium: 'Textured Art',
    dimensions: '18 x 14 in',
    description: "A heavily textured, impasto painting viewed from above, showcasing vibrant turquoise ocean water and thick, sculptural white foam crashing onto a sandy shoreline.",
    image_url: '/artworks/crashing-tide.jpeg',
  },
  {
    id: 'saffron-current',
    title: 'Saffron Current',
    price: 475,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '12 x 9 in',
    description: "A bold, abstract piece utilizing heavy impasto technique. Sweeping, textured brushstrokes in rich saffron, goldenrod, and warm orange create a sense of vibrant, flowing energy.",
    image_url: '/artworks/saffron-current.jpeg',
  },
  {
    id: 'silent-grove',
    title: 'Large Bamboo painting - Signature Piece - Quiet Strength',
    price: 0,
    notForSale: true,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '36 x 18 in',
    description: "Tall bamboo stalks rise in quiet strength while soft leaves arc around them, giving the composition a grounded stillness.",
    image_url: '/artworks/silent-grove.jpeg',
  },
  {
    id: 'amber-run',
    title: 'Where Fall Colors Flow',
    price: 145,
    collection: 'Seasonal',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A bright, seasonal landscape where a vivid blue stream cuts through a golden autumn forest. White birch trees stand prominently among the amber foliage and grasses.",
    image_url: '/artworks/amber-run.jpeg',
  },
  {
    id: 'tender-shoots',
    title: 'Gentle Leaves, Steady Stalks',
    price: 135,
    isSold: true,
    collection: 'Studio Collection',
    medium: 'Watercolor on Paper',
    dimensions: '12 x 9 in',
    description: "Slender bamboo and light leaves gather softly against open paper, giving the piece a fresh and delicate character.",
    image_url: '/artworks/tender-shoots.jpeg',
  },
  {
    id: 'interwoven-green',
    title: 'Grace Wrapped in Green',
    price: 145,
    isSold: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '12 x 9 in',
    description: "Crossing bamboo stalks and fine leaves create a woven rhythm, balancing structure and movement within a bright field of space.",
    image_url: '/artworks/interwoven-green.jpeg',
  },
  {
    id: 'azure-descent',
    title: 'Hawaii Glow by Water',
    price: 125,
    collection: 'Studio Collection',
    medium: 'Mixed Media on Canvas',
    dimensions: '9 x 12 in',
    description: "A vibrant tropical sunset rendered in rich, warm hues. Silhouetted palm trees frame a golden sun as it dips below the horizon, casting brilliant reflections across the ocean water.",
    image_url: '/artworks/azure-descent.jpeg',
  },
  {
    id: 'beach-study',
    title: 'Where Gentle Waves Return',
    price: 145,
    isSold: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A soothing coastal study featuring warm, sandy shores and gentle blue surf. The hazy, peach-toned sky creates a dreamy, atmospheric glow over the water.",
    image_url: '/artworks/beach.jpeg',
  },
  {
    id: 'cathedral-of-redwoods',
    title: 'Redwood Path to light',
    price: 0,
    notForSale: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "An inviting forest scene depicting a winding dirt trail flanked by towering, reddish-brown redwood trunks, leading deeper into a vibrant, sunlit green canopy.",
    image_url: '/artworks/cathedral-of-redwoods.jpeg',
  },
  {
    id: 'canopy-study',
    title: 'The Giant Reaches Up',
    price: 165,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A striking upward perspective of a massive tree trunk ascending toward the sky. Thick, textured bark contrasts with the bright, lush green canopy reaching overhead.",
    image_url: '/artworks/canopy.jpeg',
  },
  {
    id: 'last-light-over-the-valley',
    title: 'Sunset beyond Country Fences',
    price: 145,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A pastoral landscape showcasing vibrant green, rolling hills divided by a rustic wooden fence. A vivid sunset of pink, gold, and orange fills the sky above.",
    image_url: '/artworks/last-light-over-the-valley.jpeg',
  },
  {
    id: 'the-long-way-home',
    title: 'The Road to Serenity',
    price: 0,
    notForSale: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A peaceful countryside scene featuring a winding dirt road and rustic wooden fences. The path leads the viewer's eye through a series of lush, rolling green hills.",
    image_url: '/artworks/the-long-way-home.jpeg',
  },
  {
    id: 'autumn-whisper',
    title: 'Golden Leaves, Quiet Woods',
    price: 135,
    collection: 'Studio Collection',
    medium: 'Acrylic on Paper',
    dimensions: '9 x 12 in',
    description: "A serene autumn woodland scene focusing on the striking contrast of white birch trunks and vibrant golden canopies against a soft, atmospheric background.",
    image_url: '/artworks/autumn-whisper.jpeg',
  },
  {
    id: 'quiet-evening-lake',
    title: 'Sunset at Almaden lake park',
    price: 0,
    notForSale: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Paper',
    dimensions: '8.5 x 11.5 in',
    description: "A serene landscape featuring a solitary wooden bench overlooking a tranquil lake. Lush green foliage frames a vibrant, golden-yellow sky as the sun dips toward the horizon.",
    image_url: '/artworks/quiet-evening-lake.jpeg',
  },
  {
    id: 'minimal-branch-sunset',
    title: 'Peace Beneath Evening Skies',
    price: 115,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A minimalist composition contrasting the delicate silhouette of a bare branch against a tranquil gradient sky and calm, pale blue waters.",
    image_url: '/artworks/branch-over-waters.jpeg',
  },
  {
    id: 'cliffs-of-pacific',
    title: 'Waves of Coastal Bliss - Signature Piece',
    price: 425,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '18 x 24 in',
    description: "A breathtaking coastal landscape featuring rugged cliffs dropping into brilliant sapphire waters. A white wooden fence in the foreground invites the viewer into the expansive scene.",
    image_url: '/artworks/cliffs-of-pacific.jpeg',
  },
  {
    id: 'vibrant-horizon',
    title: 'Vibrant Horizon',
    price: 175,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '12 x 9 in',
    description: "A vivid sunset scene where fiery orange and pale pink clouds meet a calming teal ocean. The sun’s reflection shimmers across gently breaking waves rolling onto a dark shore.",
    image_url: '/artworks/vibrant-horizon.jpeg',
  },
  {
    id: 'shoreline-under-summer-clouds',
    title: 'Coastal Calm',
    price: 235,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A bright coastal landscape with a quiet sandy shore, vivid blue water, and towering white clouds drifting above. Wind-shaped trees and dark volcanic rocks anchor the composition with a distinctly tropical feel.",
    image_url: '/artworks/shoreline-under-summer-clouds.jpeg',
  },
  {
    id: 'sunbreak-over-the-sea',
    title: 'Radiant Shower of Light',
    price: 225,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '12 x 12 in',
    description: "A luminous seascape centered on sunlight breaking through layered clouds. Radiating beams and shimmering reflections stretch across the water, giving the scene a dramatic sense of openness and calm.",
    image_url: '/artworks/sunbreak-over-the-sea.jpeg',
  },
  {
    id: 'pines-by-the-pacific',
    title: 'Pines by the Pacific',
    price: 165,
    notForSale: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A peaceful coastal view framed by tall pines and a warm sandy shore. The broad blue sky and gentle surf create an airy, relaxed scene with a strong sense of stillness.",
    image_url: '/artworks/pines-by-the-pacific.jpeg',
  },
  {
    id: 'ember-horizon',
    title: 'Twilight Reflections',
    price: 245,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A dramatic ocean sunset where glowing amber light burns beneath sweeping storm clouds, reflecting in a bright path across the water.",
    image_url: '/artworks/ember-horizon.jpeg',
  },
  {
    id: 'quiet-sail',
    title: 'Peaceful Soul Voyage',
    price: 110,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '8 x 10 in',
    description: "A lone white sailboat glides across clear blue water beneath a calm sky, with distant green hills softening the horizon.",
    image_url: '/artworks/quiet-sail.jpeg',
  },
  {
    id: 'evening-across-the-bay',
    title: 'Whispers at Dusk',
    price: 85,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "Overhanging branches frame a glowing sunset bay, where the city line appears as a quiet silhouette across luminous water.",
    image_url: '/artworks/evening-across-the-bay.jpeg',
  },
  {
    id: 'desert-first-light',
    title: 'Morning over the Mountains',
    price: 65,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '8 x 10 in',
    description: "Rolling brown hills meet a clean blue sky as the first warm light of day rises over a sparse desert ridge.",
    image_url: '/artworks/desert-first-light.jpeg',
  },
  {
    id: 'still-reaching',
    title: 'Wisdom in Simplicity',
    price: 110,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '8 x 10 in',
    description: "Slender bamboo stalks and sparse leaves stand against open space, letting the piece express calm structure with elegant restraint.",
    image_url: '/artworks/still-reaching.jpeg',
  },
  {
    id: 'open-meadow',
    title: 'Timeless Resilience',
    price: 175,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '12 x 16 in',
    description: "Bold bamboo stalks rise in a closely cropped composition, emphasizing endurance, balance, and the quiet strength of mature growth.",
    image_url: '/artworks/open-meadow.jpeg',
  },
  {
    id: 'sunflower-study',
    title: 'Under the Blue Skies',
    price: 65,
    isSold: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '8 x 10 in',
    description: "Rolling green hills rest beneath an open blue sky, turning this pared-back landscape into a study in space, light, and calm.",
    image_url: '/artworks/sunflower-study.jpeg',
  },
  {
    id: 'emerald-field',
    title: 'A Field of Smiles',
    price: 120,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A bright sunflower fills the foreground while a field of smaller blooms stretches behind it, creating a warm and cheerful summer scene.",
    image_url: '/artworks/emerald-field.jpeg',
  },
  {
    id: 'cranes-in-tandem',
    title: 'Cranes in Tandem',
    price: 175,
    isSold: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "Two white cranes move together across a deep blue field, their mirrored flight conveying grace, rhythm, and companionship.",
    image_url: '/artworks/cranes-in-tandem.jpeg',
  },
  {
    id: 'three-geese-crossing',
    title: 'The Friendly Trio',
    price: 0,
    notForSale: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "Three geese stride across a sunlit field, bringing a playful sense of movement to a bright pastoral scene.",
    image_url: '/artworks/three-geese-crossing.jpeg',
  },
  {
    id: 'prairie-cloud',
    title: 'Home in the fields',
    price: 75,
    isSold: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '8 x 10 in',
    description: "A towering cloud drifts above a small red barn and open field, turning a simple rural view into a study of scale and atmosphere.",
    image_url: '/artworks/prairie-cloud.jpeg',
  },
  {
    id: 'verdant-rhythm',
    title: 'Rooted in Strength',
    price: 115,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '6 x 8 in',
    description: "Dark bamboo canes cluster in close rhythm, their sturdy vertical forms conveying grounded strength and resilience.",
    image_url: '/artworks/verdant-rhythm.jpeg',
  },
  {
    id: 'golden-rose',
    title: 'Warmth in Bloom',
    price: 85,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "A close-up yellow rose unfolds in layered petals against a dark green background, celebrating color and form.",
    image_url: '/artworks/golden-rose.jpeg',
  },
  {
    id: 'leaning-light',
    title: 'Gentle Humility',
    price: 135,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "Leaning bamboo canes and scattered leaves create a gentle diagonal flow, held together by soft light and open background space.",
    image_url: '/artworks/leaning-light.jpeg',
  },
  {
    id: 'birch-canopy',
    title: 'Spring Unfolding',
    price: 135,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "Seen from below, a bright birch trunk and spring-green leaves reach into an open blue sky, giving the painting an uplifting vertical pull.",
    image_url: '/artworks/birch-canopy.jpeg',
  },
  {
    id: 'snowline-meadow',
    title: 'Crowned in Winter, Dressed in Spring',
    price: 65,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '8 x 10 in',
    description: "A green meadow leads toward a low forest and a chain of snow-touched peaks under a clear, expansive sky.",
    image_url: '/artworks/snowline-meadow.jpeg',
  },
  {
    id: 'migration-at-dusk',
    title: 'Flight at Dusk',
    price: 65,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '8 x 10 in',
    description: "A line of white birds cuts across a glowing dusk gradient, turning a minimal sky into a quiet migration study.",
    image_url: '/artworks/migration-at-dusk.jpeg',
  },
  {
    id: 'cloudbank-coast',
    title: 'Under the Palm Shade',
    price: 165,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '9 x 12 in',
    description: "Palm fronds sweep outward from the trunk in an upward-looking tropical study filled with layered greens and clear sky.",
    image_url: '/artworks/cloudbank-coast.jpeg',
  },
  {
    id: 'mountain-barn',
    title: 'Clouds over Paradise',
    price: 245,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '12 x 9 in',
    description: "Towering white clouds rise above a calm tropical shoreline, where bright water and warm sand create an airy coastal stillness.",
    image_url: '/artworks/mountain-barn.jpeg',
  },
  {
    id: 'palm-canopy',
    title: 'Sanctuary in Green',
    price: 110,
    isSold: true,
    collection: 'Studio Collection',
    medium: 'Acrylic on Canvas',
    dimensions: '8 x 10 in',
    description: "A small refuge sits beneath a towering green mountainside, giving the scene a quiet sense of shelter, stillness, and belonging.",
    image_url: '/artworks/palm-canopy.jpeg',
  },
];
