// lib/data.ts

export const artworks = [
  {
    id: 'piece-1893',
    title: 'Alpine Stream',
    price: 400,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "A serene mountain landscape featuring a vibrant blue river winding through evergreen forests and blooming meadows.",
    image_url: '/artworks/alpine-stream.jpeg',
  },
  {
    id: 'october-bend',
    title: 'October Bend',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '36 x 24 in',
    description: "A river bend framed by saturated reds and golds, painted with the soft haze and stillness of peak October.",
    image_url: '/artworks/october-bend.jpeg',
  },
  {
    id: 'piece-1903',
    title: 'Pastel Horizon',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "Soft pastel light settles over an open shoreline, where warm sand and calm water meet beneath a luminous horizon.",
    image_url: '/artworks/pastel-horizon.jpeg',
  },
  {
    id: 'sunbreak',
    title: 'Sunbreak',
    price: 500,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "A break in the clouds sends a clear path of light across open water, balancing drama with calm restraint.",
    image_url: '/artworks/sunbreak.jpeg',
  },
  {
    id: 'piece-1925',
    title: 'Crashing Tide',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '14 x 18 in',
    description: "A highly textured, dynamic piece capturing the frothy white crests of azure ocean waves hitting the shore.",
    image_url: '/artworks/crashing-tide.jpeg',
  },
  {
    id: 'saffron-current',
    title: 'Saffron Current',
    price: 475,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "A warm abstract built from sweeping saffron and ochre strokes, emphasizing motion, texture, and directional flow.",
    image_url: '/artworks/saffron-current.jpeg',
  },
  {
    id: 'pacific-palms',
    title: 'Pacific Palms',
    price: 500,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '18 x 24 in',
    description: "A simple palm-lined coast set against an expansive sky, capturing the easy openness of a Pacific shoreline.",
    image_url: '/artworks/pacific-palms.jpeg',
  },
  {
    id: 'bamboo-study-i',
    title: 'Bamboo Study I',
    price: 520,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '18 x 36 in',
    description: "A close bamboo study that emphasizes structure, weight, and tonal variation within a restrained vertical composition.",
    image_url: '/artworks/bamboo-study-i.jpeg',
  },
  {
    id: 'canopy-in-flame',
    title: 'Canopy in Flame',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '24 x 36 in',
    description: "An upward view into a bright canopy of orange and vermilion, turning a familiar tree into something monumental.",
    image_url: '/artworks/canopy-in-flame.jpeg',
  },
  {
    id: 'piece-1957',
    title: 'Emerald Lagoon',
    price: 480,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "Lush tropical greens and reflective blue water create a quiet sense of escape in this serene lagoon scene.",
    image_url: '/artworks/emerald-lagoon.jpeg',
  },
  {
    id: 'piece-1958',
    title: 'Whispering Pines Cove',
    price: 450,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '8 x 10 in',
    description: "A sandy path opens into a quiet cove lined with wind-shaped pines, rendered with an airy watercolor lightness.",
    image_url: '/artworks/whispering-pines-cove.jpeg',
  },
  {
    id: 'amber-run', 
    title: 'Amber Run',
    price: 520,
    collection: 'Seasonal',
    medium: 'Oil on Canvas',
    dimensions: '9 x 12 in',
    description: "A bright stream winds through amber grasses and pale trunks, carrying cool blue water through a warm autumn field.",
    image_url: '/artworks/amber-run.jpeg', 
  },
  {
    id: 'bamboo-study-ii',
    title: 'Bamboo Study II',
    price: 550,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: '10.5 x 13.5 in',
    description: "A spare bamboo composition with delicate linework and open negative space, conceived as a quieter companion study.",
    image_url: '/artworks/bamboo-study-ii.jpeg',
  },
  {
    id: 'bamboo-study-iii',
    title: 'Bamboo Study III',
    price: 560,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "A broader bamboo arrangement that leans into layered stems and airy branching, extending the series with a fuller, more expansive composition.",
    image_url: '/artworks/bamboo-study-iii.jpeg',
  },
  {
    id: 'azure-descent',
    title: 'Azure Descent',
    price: 525,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "A crisp coastal scene where ocean-blue water gathers around dark rock formations at the foot of a windswept cliff.",
    image_url: '/artworks/azure-descent.jpeg',
  },
  {
    id: 'beach-study',
    title: 'Beach Study',
    price: 465,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "A pared-back coastal study focused on warm sand, soft surf, and the quiet glow of late light over open water.",
    image_url: '/artworks/beach.jpeg',
  },
  {
    id: 'cathedral-of-redwoods',
    title: 'Cathedral of Redwoods',
    price: 540,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "Towering redwoods frame a quiet forest path, drawing the eye upward through luminous green canopies and warm woodland earth.",
    image_url: '/artworks/cathedral-of-redwoods.jpeg',
  },
  {
    id: 'canopy-study',
    title: 'Canopy Study',
    price: 505,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "An upward-facing tree study that emphasizes trunk movement and dense green foliage, treating the canopy as a single, immersive field of form.",
    image_url: '/artworks/canopy.jpeg',
  },
  {
    id: 'light-through-silence',
    title: 'Light Through Silence',
    price: 520,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "Soft shafts of morning light cut through a dense stand of forest trees, giving the scene a hushed and atmospheric stillness.",
    image_url: '/artworks/light-through-silence.jpeg',
  },
  {
    id: 'last-light-over-the-valley',
    title: 'Last Light Over the Valley',
    price: 495,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "A glowing pink and gold sunset settles over open land, capturing the final warmth of day before dusk takes hold.",
    image_url: '/artworks/last-light-over-the-valley.jpeg',
  },
  {
    id: 'the-long-way-home',
    title: 'The Long Way Home',
    price: 545,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "Rolling green hills and a winding fenced path create a pastoral landscape full of movement, distance, and calm.",
    image_url: '/artworks/the-long-way-home.jpeg',
  },
  {
    id: 'ancient-quiet',
    title: 'Ancient Quiet',
    price: 510,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "A close forest study centered on the texture and presence of old-growth trunks, with layered greens suggesting depth and stillness.",
    image_url: '/artworks/ancient-quiet.jpeg',
  },
  {
    id: 'pacific-edge',
    title: 'Pacific Edge',
    price: 530,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "Bright coastal blues and rugged rock forms meet along a dramatic shoreline, evoking the clear intensity of the Pacific coast.",
    image_url: '/artworks/pacific-edge.jpeg',
  },
  {
    id: 'autumn-whisper',
    title: 'Autumn Whisper',
    price: 500,
    collection: 'Studio Collection',
    medium: 'Oil on Canvas',
    dimensions: 'Available on request',
    description: "Delicate birch trunks and restrained golden foliage create a quiet autumn composition with a light, airy sense of space.",
    image_url: '/artworks/autumn-whisper.jpeg',
  }
];
